-- ===========================================
-- DEPRECATED: This migration is no longer valid.
-- Date deprecated: 2026-02-26
-- Reason: Level 1 auth uses is_admin BOOLEAN, NOT role VARCHAR.
--         The role column was removed by migration_auth_level1_fix.sql.
--         Permissions column was kept and is added in schema.sql.
-- ===========================================
-- DO NOT RUN THIS FILE.
-- See: database/migrations/migration_auth_level1_fix.sql
-- See: database/migrations/migration_fix_is_verified.sql
